spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/ai_db_analyst
spring.datasource.username=vivek
spring.datasource.password=Vivek@2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true