spring.application.name=backend
server.port = 8081
server.address=0.0.0.0
spring.datasource.url=jdbc:mysql://localhost:3306/taskDB
spring.datasource.username=vivek
spring.datasource.password=Vivek@2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vivek.narawade@aissmsioit.org
spring.mail.password=mqkiqxvimsvcgoob
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.mail=DEBUG
logging.level.org.apache.commons.mail=DEBUG

#Hikari config
#pool size(can have 30 connections)
spring.datasource.hikari.maximum-pool-size=30
#initially it create 10
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000









#SECURITY CONFIG
spring.security.user.name =Vivek
spring.security.user.password=123

jwt.secret=your-super-secret-key-very-long-and-secure-123456
jwt.access.expiration=15m
jwt.refresh.expiration=7d